openapi: 3.0.1
info:
  version: "1.0.0"
  title: "Marketplace API"
servers:
  - url: "http://localhost:3000"
paths:
  /register:
    post:
      summary: Registers a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./src/schemas/registerSchema.json"
      responses:
        201:
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: "./src/schemas/userSchema.json"
  /login:
    post:
      summary: Performs user login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./src/schemas/registerSchema.json"
      responses:
        200:
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: The JSON Web Token for the authenticated user
        401:
          description: Login error
          content:
            application/json:
              schema:
                $ref: "./src/schemas/messageSchema.json"
          examples:
            BadCredentials:
              value:
                summary: "Login error"
                userAction: "Retry"
                description: "Email and password are not valid"
  /logout:
    post:
      summary: Performs user logout
      security:
        - BearerAuth: []
      requestBody:
        description: The request must include an Authorization header with a valid Bearer token.
      responses:
        200:
          description: Logout successful, token invalidated
          content: {}
        400:
          description: Bad token
          content:
            application/json:
              schema:
                $ref: "./src/schemas/messageSchema.json"
        401:
          description: Not authorized or missing Authorization header
          content:
            application/json:
              schema:
                $ref: "./src/schemas/messageSchema.json"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
