version: "3"

services:
  redis:
    image: "redis:latest"
    restart: unless-stopped
    ports:
      - 6379:6379

  mongo:
    image: "mongo:latest"
    restart: unless-stopped
    volumes:
      - ~/dev/mongo-data:/data/db
    ports:
      - 27017:27017

  minio:
    image: "minio/minio"
    restart: unless-stopped
    volumes:
      - ~/dev/minio-data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data
