version: "3.3"
services:
  db:
    image: mongo:4.2-bionic
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ashtrei_mongodb_data:/data/db
  server:
    image: early-signup:1.0
    restart: unless-stopped
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      MONGO_URL: mongodb://admin:password@db:27017/
volumes:
  ashtrei_mongodb_data:
