"""nullable user

Revision ID: 6465400bdbc2
Revises: 67cd2ed2b263
Create Date: 2023-10-22 00:13:01.343239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6465400bdbc2'
down_revision: Union[str, None] = '67cd2ed2b263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
